# Site
repository: luisdimottabre/luisdimottabre.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Dimotta Bré
title: Economista Especializado en Finanzas
email: luisndimotta@gmail.com
#phone: +549-2213068543

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: luisdimottabre
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: luis-dimotta-bre
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: ¿Quién soy?
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, me llamo Luis y soy un economista graduado en la Universidad Nacional de La Plata. Tengo una pasión
  por las finanzas de la manera en que la define Robert Shiller, "una ingenieria para lograr objetivos". Estoy buscando la oportunidad de desarrollar mi carrera en el Mercado de Capitales, aunque tambien considero que la Energía y los Agronegocios tienen su rol en el futuro. Hasta este punto de mi vida, he trabajado en consultorías y en la facultad de economía, desarrollando disciplina y liderazgo en el proceso.

  Soy más habilidoso con: <mark>STATA</mark>, <mark>Python</mark> y <mark>R</mark>.


#  - title: Proyectos # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm #        very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
content:
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Consultor pasante - Zaffi
        sub_title: Coequipo
        caption: Agosto 2024 - Diciembre 2024
        description: | # this will include new lines to allow paragraphs
          Participé en la provisión de servicios de consultoría para la empresa de aberturas Zaffi, enfocados en la optimización de procesos y el perfeccionamiento de estructuras organizacionales. Colaboré en un equipo auditor en la identificación de ineficiencias operativas y el diseño de soluciones estratégicas, contribuyendo directamente a la mejora de la eficiencia y rentabilidad de los negocios de los clientes.

      - layout: left
        title: Becario de investigación - Programa Pulso
        sub_title: Secretaría de Extensión Universitaria
        caption: Septiembre 2023 - Mayo 2024
        description: | # this will include new lines to allow paragraphs
          Contribuí al diseño y armado técnico-metodológico de un directorio integral de ONGs para La Plata y alrededores, ampliando la base de datos de 100 a más de 1.000 organizaciones. Esto se logró mediante la aplicación de técnicas avanzadas de web-scraping y rigurosos procesos de validación de datos, mejorando significativamente la disponibilidad y calidad de información para la Secretaría de Extensión Universitaria.

      - layout: left
        title: Startup Advisor
        sub_title: Usina de Ideas
        caption: Abril 2023 - Febrero 2024
        description: | # this will include new lines to allow paragraphs
          Responsable de guiar a más de 2 startups a través del programa de aceleración, estableciendo objetivos claros y desarrollando planes de acción para alcanzar hitos clave de negocio y financiamiento. Asesoré junto a un equipo de expertos en la formulación de estrategias de crecimiento, optimización de modelos de negocio y preparación para rondas de inversión, contribuyendo al desarrollo y escalabilidad de los proyectos.

      - layout: left
        title: Ayudante adjunto - Introducción a la economía
        sub_title: Universidad Nacional de La Plata
        caption: Abril 2022 - Agosto 2024
        description: | # this will include new lines to allow paragraphs
          Apoyé y asistí a más de 200 ingresantes anuales en la comprensión de los fundamentos económicos y el desarrollo de sus capacidades analíticas, contribuyendo a su éxito en la asignatura y colaboré activamente en la enseñanza y resolución de dudas, facilitando la adaptación de los estudiantes al entorno universitario y a los contenidos de la materia.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Licenciatura en Ciencias Económicas
        sub_title: Universidad Nacional de La Plata
        caption: Marzo 2018 - Diciembre 2024
        quote: >
          Todavía tengo que ver un problema, por complicado que sea, que al mirarlo de forma correcta no se vuelva aún más complicado.
        description: | # this will include new lines to allow paragraphs
          La licenciatura me dio pocas herramientas duras (Stata y R fueron de las pocas), pero me dio la herramienta de los modelos y los paradigmas, la herramienta blanda de ver los fenómenos de cierta manera, porque no todo lo resuelve un martillo si no sabes si tenes que martillar, serruchar o hacer un agujero. Entender la economía es comprender que las multitudes tienen pasiones, no cerebros. Es precisamente esa comprensión la que busco aplicar para trascender el análisis y los paradigmas.

  - title: Cursos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FMAX: Financial Market Analysis
        sub_title: Fondo Monetario Internacional
        caption: Febrero 2025 - Abril 2025
        description: |
          Instrumentos financieros, estructura temporal de tasas de interés, asignación de portafolio y gestión de riesgo.

      - layout: left
        title: Programa de formación
        sub_title: Bolsa de Comercio de Rosario
        caption: Mayo 2023 - Octubre 2024
        description: |
          Especialización en Mercado de Capitales, Trading de derivados y Administración y Back-Office del mercado de granos.

      - layout: left
        title: Seminario de Data Science con Python
        sub_title: Universidad Nacional de La Plata
        caption: Junio 2022 - Diciembre 2022
        description: |
          Programa enfocado a la ciencia de datos, inteligencia artificial y machine learning usando Python.

  - title: ¿Qué hago cuando no estoy en frente de una pantalla?
    layout: text
    content: | # this will include new lines to allow paragraphs
        *Lo que busco por encima de todo es la grandeza, lo que es grande es siempre bello*

        Cuando no estoy sentado frente a mi escritorio suelo vivir la vida en un gimnasio, pateando una pelotita o buscando la verdad en las cosas. Junto a mis intereses en finanzas y macroeconomía, suelo explorar los terrenos de:
            - Fútbol
            - Ciencia ficción (lean el "Problema de los Tres Cuerpos")
            - Fantasía (lean el "Principe de las Espinas")
            - Historia (lean la saga "Los reyes malditos")
            - Escalada

            Por último, les dejo una de mis pinturas favoritas de Nasmith:

            ![Tuor llega a Gondolin](images/gondolin.jpeg)

# Footer
footer_show_references: true
# references_title:

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
